;;; stickyfunc-enhance-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from stickyfunc-enhance.el

(autoload 'semantic-stickyfunc-fetch-stickyline "stickyfunc-enhance" "\
Make the function at the top of the current window sticky.
Capture its function declaration, and place it in the header line.
If there is no function, disable the header line.")
(register-definition-prefixes "stickyfunc-enhance" '("stickyfunc-enhance--"))

;;; End of scraped data

(provide 'stickyfunc-enhance-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stickyfunc-enhance-autoloads.el ends here
